#!/usr/local/bin/ansible-playbook --inventory=inventory
- name: 'Mirror content using oc-mirror | mirror-operators.yml'
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3.6
    module: "content-mirror"
    ansible_name_module: " Miror Content using oc-mirror | {{ module }}"

  vars_files:
    - 'vars/vault.yml'
    - 'vars/registry.yml'
    - 'vars/content-mirror.yml'
  
  pre_tasks:
    - name: Ensure required oc-mirror binary is installed on host
      when:
        - not oc_mirror_cli is defined or oc_mirror_cli == ''
      block:
        - name: '{{ ansible_name_module }} | command:which | Check if oc-mirror is installed'
          ansible.builtin.shell: >
            which oc-mirror
          ignore_errors: yes
          register: ocmirror_binary

        - name: '{{ ansible_name_module }} | set_fact |  oc_mirror_cli'
          ansible.builtin.set_fact:
            oc_mirror_cli: "{{ ocmirror_binary.stdout }}"
          when:
            - ocmirror_binary is defined
            - ocmirror_binary.rc is defined
            - ocmirror_binary.rc == 0
            - ocmirror_binary.stdout is defined
            - ocmirror_binary.stdout != ''

  tasks:
    - name: '{{ ansible_name_module }} | COnditionally create imageset config files'
      when:
        - imageset_config_files_to_create is defined
        - imageset_config_files_to_create is mapping
        - imageset_config_files_to_create.keys() is defined
        - imageset_config_files_to_create.keys() | length > 0
      block:
        - name: '{{ ansible_name_module }} | ansible.builtin.include_tasks | Prcess content imageset config files creation'
          ansible.builtin.include_tasks: tasks/create-imageset-manifests-for-single-operators.yml

        - name: '{{ ansible_name_module }} | ansible.builtin.set_fact | set image_set_config_files '
          ansible.builtin.set_fact:
            imageset_config_files: "{{ created_imageset_config_files }}"

    - name: '{{ ansible_name_module }} | ansible.builtin.shell | Prcess content mirror within imageset  catalogs config files '
      ansible.builtin.include_tasks: tasks/process-content-mirror-using-oc-mirror.yml
      loop: "{{ imageset_config_files }}"
      vars:
        imageset_config_file: "{{ item }}"
      register: all_content_mirrored

    - name: '{{ ansible_name_module }} | Print Content Mirror output'
      ansible.builtin.debug:
        var: all_content_mirrored.results
        verbosity: 2

