#!/usr/local/bin/ansible-playbook --inventory=inventory
- name: ' Konductor | Provision UPI Infra | mirror-operators.yml'
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3.6
    module: "mirror-operators"
    ansible_name_module: " Konductor | Provision UPI Infra | {{ module }}"
  vars_files:
    - 'vars/vault.yml'
    - 'vars/registry.yml'

  pre_tasks:
    - name: Install required dependencies 
      become: yes
      yum:
        name:
          - python3-libselinux 
        state: present

    - name: '{{ ansible_name_module }} | pip install | install required module'
      pip:
        name: jinja2

  tasks:
    - name: '{{ ansible_name_module }} | Download, install and configure grpcurl '
      when:
        - pull_all is defined
        - pull_all | bool
      block:
        - name: '{{ ansible_name_module }} | get_url | '
          get_url:
            url: "{{ grpcurl_binary_download_url }}"
            dest: "{{ temp_dir }}"
            mode: 0755
            force: true
            validate_certs: false
          register: grpcurl_downloaded

        - name: '{{ ansible_name_module }} | unarchive | unpack grpcurl archive'
          become: yes
          unarchive:
            src: "{{ temp_dir }}/{{ grpcurl_binary_downloaded_artifact }}"
            dest: "{{  grpcurl_binary | dirname }}"
            mode: 0755
            remote_src: true
            validate_certs: false
          register: grpcurl_archive_installed

    - name: '{{ ansible_name_module }} | file:directory | Ensure all directory exist'
      command: >
        podman rm -f {{ registry_container_name }}
      ignore_errors: yes
      register: registry_container_removed

    - name: '{{ ansible_name_module }} | file:directory | Ensure all directory exist'
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ registry_container_dir }}"
        - "{{ dir_bundle_location }}"
        - "{{ dir_bundle_staging }}"
        - "{{ dir_bundle_staging }}/run"
        - "{{ dir_bundle_staging }}/scripts"

    - name: '{{ ansible_name_module }} | Download, install and configure opm '
      when:
        - install_opm is defined
        - install_opm | bool
      block:
        - name: '{{ ansible_name_module }} | get_url | download opm binary'
          get_url:
            url: "{{ opm_binary_download_url }}"
            dest: "{{ temp_dir }}"
            mode: 0755
            force: true
            validate_certs: false
          register: opm_downloaded

        - name: '{{ ansible_name_module }} | unarchive | unpack opm archive'
          become: yes
          unarchive:
            src: "{{ temp_dir }}/{{ opm_binary_downloaded_artifact }}"
            dest: "{{  opm_binary | dirname }}"
            mode: 0755
            remote_src: true
            validate_certs: false
          register: opm_archive_installed

        - name: '{{ ansible_name_module }} | copy | copy opm binary to {{ dir_bundle_staging }}/run '
          copy:
            src: "{{ opm_binary }}"
            dest: "{{ dir_bundle_staging }}/run/{{ opm_binary | basename }}"
            force: yes
            mode: '0755'
          register: opm_archive_copied

    - name: '{{ ansible_name_module }} | Generate list of operator for each index'
      when:
        - generate_operator_list is defined
        - generate_operator_list | bool 
        - item.key is defined and item.key != ""
        - item.value.source is defined and item.value.source != ""
        - item.value.host_port is defined and item.value.host_port|int > 0
        - item.value.container_port is defined and item.value.container_port|int > 0
      block:
        - name: '{{ ansible_name_module }} | podman:run | Start operator-index container '
          command: podman run -d --name operator_collector_{{ item.key  }} \
            -p {{ item.value.host_port }}:{{ item.value.container_port }}  {{ item.value.source }}
          with_dict:
            - "{{ operator_registries_to_mirror }}"

        - name: '{{ ansible_name_module }} | Create Package index '
          shell: >
            grpcurl -plaintext localhost:{{ item.value.host_port }} api.Registry/ListPackages \
            > "{{ dir_bundle_location | d('/tmp') }}/packages-{{ item.key }}.out"
          with_dict:
            - "{{ operator_registries_to_mirror }}"
          register: pkg_idx_out

        - name: '{{ ansible_name_module }} | podman:rm | Remove operator-index container '
          command: podman rm -f operator_collector_{{ item.key }}
          with_dict:
            - "{{ operator_registries_to_mirror }}"

        - name: '{{ ansible_name_module }} | cat | derive operator list from package manifest file '
          shell: cat "{{ dir_bundle_location | d('/tmp') }}/packages-{{ item.key }}.out" | jq .name | sed -e 's~"~~g'  > {{ dir_bundle_staging }}/{{ item.key }}
          with_dict:
            - "{{ operator_registries_to_mirror }}"
          register: operator_list_raw

    - name: '{{ ansible_name_module }} | podman:login | Login to RH container registry'
      no_log: true
      command: >
         podman login -u {{ default_operator_registry_username }} \
         -p {{ default_operator_registry_password }} \
         --authfile {{ hostvars[inventory_hostname].ansible_env.HOME }}/.docker/oprconfig.json \
          {{ default_operator_registry }}
      register: authfile_created

    - name: '{{ ansible_name_module }} | podman:login | Login to extra registry'
      no_log: true
      command: >
        podman login -u {{ default_operator_registry_username }} \
          -p {{ default_operator_registry_password }} \
          --authfile {{ hostvars[inventory_hostname].ansible_env.HOME }}/.docker/oprconfig.json \
          {{ item.value.image_registry }}
      with_dict:
        - "{{ operator_registries_to_mirror }}"
      when:
        - item.key is defined and item.key != ""
        - item.value.source is defined and item.value.source != ""
        - item.value.image_registry is defined and item.value.image_registry != ""

    - name: '{{ ansible_name_module }} | file |  set permission on authfile for registry'
      file:
        path: '{{ hostvars[inventory_hostname].ansible_env.HOME }}/.docker/oprconfig.json'
        mode: '0644'

    - name: '{{ ansible_name_module }} | set_fact |  authfile for registry'
      set_fact:
        operator_registry_pull_secret_file: "{{ hostvars[inventory_hostname].ansible_env.HOME }}/.docker/oprconfig.json"

    - name: '{{ ansible_name_module }} | file:directory | Ensure the images staging directory exist'
      file:
        path: "{{ item }}"
        state: directory
        mode: 0755
      loop:
        - "{{ dir_bundle_staging }}"
        - "{{ registry_container_dir }}"

    - name: '{{ ansible_name_module }} | podman:run | Start registry container '
      command: podman run -d --name {{ registry_container_name }} \
        -p 5000:5000 -v {{ registry_container_dir }}:/var/lib/registry \
          {{ registry_container_image }}

    - name: '{{ ansible_name_module }} | copy | copy content template files to staging location '
      copy:
        src: "{{ item }}"
        dest: "{{ dir_bundle_staging }}/{{ item | basename }}"
        force: yes
        mode: 0644
      with_items:
        - openshift-disconnected-operators/known-bad-images
        - openshift-disconnected-operators/image-content-source-template
        - openshift-disconnected-operators/catalog-source-template

    - name: '{{ ansible_name_module }} | copy | copy python modules into the script directory for execution '
      copy:
        src: "{{ item }}"
        dest: "{{ dir_bundle_staging }}/scripts/{{ item | basename }}"
        force: yes
        mode: '0755'
      with_items:
        - openshift-disconnected-operators/mirror-operator-catalogue.py
        - openshift-disconnected-operators/upgradepath.py

    - name: '{{ ansible_name_module }} | file | create operator-yaml-file '
      file:
        path: "{{ dir_bundle_staging }}/{{ item.key }}{{ '.yaml' }}"
        state: touch
        mode: '0655'
      with_dict:
        - "{{ operators_to_mirror }}"
      when:
        - item.key is defined and item.key != ""
        - item.value.mirror is defined and item.value.mirror | bool
        - item.value.source is defined and item.value.source != ""
        - item.value.upgrade is defined and item.value.upgrade | bool

    - name: '{{ ansible_name_module }} | Add Markers to mark operators'
      lineinfile:
        path: "{{ dir_bundle_staging }}/{{ item.key }}{{ '.yaml' }}"
        line: "# BEGIN ANSIBLE MANAGED BLOCK Adding operators Block"
      with_dict:
        - "{{ operators_to_mirror }}"
      when:
        - item.key is defined and item.key != ""
        - item.value.mirror is defined and item.value.mirror | bool
        - item.value.source is defined and item.value.source != ""
        - item.value.upgrade is defined and item.value.upgrade | bool

    - name: '{{ ansible_name_module }} | Add Markers to mark operators'
      lineinfile:
        path: "{{ dir_bundle_staging }}/{{ item.key }}{{ '.yaml' }}"
        line: "# END ANSIBLE MANAGED BLOCK Adding operators Block"
      with_dict:
        - "{{ operators_to_mirror }}"
      when:
        - item.key is defined and item.key != ""
        - item.value.mirror is defined and item.value.mirror | bool
        - item.value.source is defined and item.value.source != ""
        - item.value.upgrade is defined and item.value.upgrade | bool

    - name: '{{ ansible_name_module }} | Add operators block'
      blockinfile:
        marker: "# {mark} ANSIBLE MANAGED BLOCK Adding operators Block"
        path: "{{ dir_bundle_staging }}/{{ item.key }}{{ '.yaml' }}"
        state: present
        block: |
          operators:
            name: {{ item.key }}
            start_version: {{ item.value.start_version }}
      with_dict:
        - "{{ operators_to_mirror }}"
      when:
        - item.key is defined and item.key != ""
        - item.value.mirror is defined and item.value.mirror | bool
        - item.value.source is defined and item.value.source != ""
        - item.value.upgrade is defined and item.value.upgrade | bool

    - name: '{{ ansible_name_module }} | Remove End Markers'
      lineinfile:
        path: "{{ dir_bundle_staging }}/{{ item.key }}{{ '.yaml' }}"
        line: "# END ANSIBLE MANAGED BLOCK Adding operators Block"
        state: absent
      with_dict:
        - "{{ operators_to_mirror }}"
      when:
        - item.key is defined and item.key != ""
        - item.value.mirror is defined and item.value.mirror | bool
        - item.value.source is defined and item.value.source != ""
        - item.value.upgrade is defined and item.value.upgrade | bool

    - name: '{{ ansible_name_module }} | Remove Begin  Markers'
      lineinfile:
        path: "{{ dir_bundle_staging }}/{{ item.key }}{{ '.yaml' }}"
        line: "# BEGIN ANSIBLE MANAGED BLOCK Adding operators Block"
        state: absent
      with_dict:
        - "{{ operators_to_mirror }}"
      when:
        - item.key is defined and item.key != ""
        - item.value.mirror is defined and item.value.mirror | bool
        - item.value.source is defined and item.value.source != ""
        - item.value.upgrade is defined and item.value.upgrade | bool

    - name: '{{ ansible_name_module }} | Remove empty start_version tags'
      lineinfile:
        path: "{{ dir_bundle_staging }}/{{ item.key }}{{ '.yaml' }}"
        regexp: "start_version: ''"
        state: absent
      with_dict:
        - "{{ operators_to_mirror }}"
      when:
        - item.key is defined and item.key != ""
        - item.value.mirror is defined and item.value.mirror | bool
        - item.value.source is defined and item.value.source != ""
        - item.value.upgrade is defined and item.value.upgrade | bool

    - name: '{{ ansible_name_module }} | file:directory | ensure ouput directory exits for each of indices being processed'
      file:
        path: "{{ dir_bundle_staging }}/{{ item.key }}-publish"
        state: directory
        mode: 0755
      with_dict:
        - "{{ operators_to_mirror }}"
      when:
        - item.key is defined and item.key != ""
        - item.value.mirror is defined and item.value.mirror | bool
        - item.value.source is defined and item.value.source != ""

    - name: Mirror operators using Arvin's python script
      script: >
        {{ dir_bundle_staging }}/scripts/mirror-operator-catalogue.py \
              --catalog-version=1.0.0 \
              --authfile={{ operator_registry_pull_secret_file }} \
              --registry-olm=localhost:5000 \
              --registry-catalog=localhost:5000 \
              --icsp-scope=namespace \
              --run-dir={{ dir_bundle_staging }} \
              --operator-image-name={{ item.key }} \
              --operator-catalog-image-url={{ item.value.source.split(':')[0] }}  \
              --opm-path={{ opm_binary }} \
              --custom-operator-catalog-name=custom-{{ item.key }} \
              --oc-cli-path={{ openshift_cli }} \
              --ocp-version={{ ocp_release_version }} \
              --output={{ item.key }}-publish \
              --operator-channel={{ item.value.source.split(':')[1] }} \
              --operator-yaml-file={{ dir_bundle_staging }}/{{ item.key }}{{ '.yaml' }}
      args:
        executable: python3
        chdir: "{{ dir_bundle_staging }}/scripts/"
      environment:
        - PYTHONPATH: "{{ dir_bundle_staging }}/scripts/"
      with_dict:
        - "{{ operators_to_mirror }}"
      when:
        - item.key is defined and item.key != ""
        - item.value.mirror is defined and item.value.mirror | bool
        - item.value.source is defined and item.value.source != ""
        - item.value.upgrade is defined and item.value.upgrade | bool

    - name: Mirror operators using Arvin's python script
      script: >
        {{ dir_bundle_staging }}/scripts/mirror-operator-catalogue.py \
              --catalog-version=1.0.0 \
              --authfile={{ operator_registry_pull_secret_file }} \
              --registry-olm=localhost:5000 \
              --registry-catalog=localhost:5000 \
              --icsp-scope=namespace \
              --run-dir={{ dir_bundle_staging }} \
              --operator-image-name={{ item.key }} \
              --operator-catalog-image-url={{ item.value.source.split(':')[0] }}  \
              --opm-path={{ opm_binary }} \
              --custom-operator-catalog-name=custom-{{ item.key }} \
              --oc-cli-path={{ openshift_cli }} \
              --ocp-version={{ ocp_release_version }} \
              --output={{ item.key }}-publish \
              --operator-channel={{ item.value.source.split(':')[1] }} \
              --operator-list={{ item.key }}
      args:
        executable: python3
        chdir: "{{ dir_bundle_staging }}/scripts/"
      environment:
        - PYTHONPATH: "{{ dir_bundle_staging }}/scripts/"
      with_dict:
        - "{{ operators_to_mirror }}"
      when:
        - item.key is defined and item.key != ""
        - item.value.mirror is defined and item.value.mirror | bool
        - item.value.source is defined and item.value.source != ""
        - not item.value.upgrade is defined or not item.value.upgrade | bool

    #######################This is to fix some discrepancies seen after images have been mirrored ############################
    ###########################
    #  When a manifest is part of a list and the manifest is mirrored by itself there seems to be a disconnect
    #  between what is in the mapping file and what is mirrored. So it appears that for cases like that we
    #  need to do a second pass and mirror all manifest is the list.
    #  As an example look at openshift4/ose-kube-rbac-proxy@sha256:6d0286b8a8f6f3cd9d6cd8319400acf27b70fbb52df5808ec6fe2d9849be7d8c
    #  it is part of a list and on the file system the only image left using the Arvin method is
    #  ca290fbe3a0de7ac7a513322d466fd26124c56851c027430a8c1dbe2b30f21f6 which does not match the manifest above
    #  when you attempt to push using the digest in the mapping file you get an error saying unknown manifest
    #  That is what this second pass is fixing
    #  #####################################################################################################
    - name: '{{ ansible_name_module }} | shell:cat | load mapping.txt file'
      shell: cat {{ dir_bundle_staging }}/{{ item.key }}-publish/mapping.txt
      with_dict:
        - "{{ operators_to_mirror }}"
      when:
        - item.key is defined and item.key != ""
        - item.value.mirror is defined and item.value.mirror | bool
        - item.value.source is defined and item.value.source != ""
      register: images_from_mapping

    - name: '{{ ansible_name_module }} | set_fact |create list of all images mirrored'
      set_fact:
        mirrored_images_list: "{{ mirrored_images_list | default([]) + item.stdout_lines }}"
      loop: "{{ images_from_mapping.results }}"
      when:
        - not item.skipped is defined
        - not item.skip_reason is defined
        - item.stdout_lines is defined
        - item.stdout_lines | length > 0
      register: images_mirrored_list_created

    - name: '{{ ansible_name_module }} | oc image mirror | mirror images using the mapping files'
      command: >
        oc image mirror {{ item.split('=')[0] }} \
           localhost:5000/{{ ((item.split('=')[0]).split('/')[1:] | join('/')).split('@sha256')[0] }} \
           --keep-manifest-list=true --insecure=true \
           -a {{ operator_registry_pull_secret_file }}
      loop: "{{ mirrored_images_list }}"
      register: images_mirrored_2nd_pass

    ####################### End Fix ############################
    
    - name: '{{ ansible_name_module }} | block | copy manifest files to container storage location'
      when:
        - bundle is defined
        - bundle | bool
      block:
        - name: '{{ ansible_name_module }} | command: cp | copy manifest files '
          copy:
            src: "{{ dir_bundle_staging }}/{{ item.key }}-publish"
            dest: "{{ registry_container_dir }}"
            force: yes
          with_dict:
            - "{{ operators_to_mirror }}"
          when:
            - item.key is defined and item.key != ""
            - item.value.mirror is defined and item.value.mirror | bool
            - item.value.source is defined and item.value.source != ""

        - name: '{{ ansible_name_module }} | archive:xz | create operator image bundle '
          become: yes
          command: >
            tar -c --use-compress-program='pigz -9' -v \
              -f {{ dir_bundle_location }}/{{ bundle_file_name }} \
              -C {{ registry_container_dir }} .
          args:
            warn: false
            chdir: "{{ registry_container_dir }}/"
