#!/usr/local/bin/ansible-playbook --inventory=inventory
- name: ' Push Content to registry using oc-mirror | push-content-using-oc-mirror.yml'
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3.6
    module: "push-content-to-registry"
    ansible_name_module: "Push content to registry | {{ module }}"

  vars_files:
    - 'vars/vault.yml'
    - 'vars/registry.yml'
  
  pre_tasks:
    - name: Ensure required oc-mirror binary is installed on host
      when:
        - not oc_mirror_cli is defined or oc_mirror_cli == ''
      block:
        - name: '{{ ansible_name_module }} | ansible.builtin.command:which | Check if oc-mirror is installed'
          ansible.builtin.shell: >
            which oc-mirror
          ignore_errors: yes
          register: ocmirror_binary

        - name: '{{ ansible_name_module }} | set_fact |  oc_mirror_cli'
          ansible.builtin.set_fact:
            oc_mirror_cli: "{{ ocmirror_binary.stdout }}"
          when:
            - ocmirror_binary is defined
            - ocmirror_binary.rc is defined
            - ocmirror_binary.rc == 0
            - ocmirror_binary.stdout is defined
            - ocmirror_binary.stdout != ''

    - name: '{{ ansible_name_module }} | ansible.builtin.command:which | Check if podman is installed'
      block:
        - name: '{{ ansible_name_module }} | ansible.builtin.command:which | Check if oc-mirror is installed'
          ansible.builtin.shell: >
            which podman
          ignore_errors: yes
          register: podman_binary

        - name: '{{ ansible_name_module }} | set_fact |  podman_cli'
          ansible.builtin.set_fact:
            podman_cli: "{{ podman_binary.stdout }}"
          when:
            - podman_binary is defined
            - podman_binary.rc is defined
            - podman_binary.rc == 0
            - podman_binary.stdout is defined
            - podman_binary.stdout != ''

  tasks:
    - name: '{{ ansible_name_module }} | file:directory | Ensure the images staging directory exist'
      become: yes
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: 0777
      loop:
        - "{{ registry_container_dir }}"
        - "{{ dir_bundle_location }}"

    - name: Set Selinux Context flag on Container Drectory  mount point
      become: yes
      sefcontext:
        target: "{{ registry_container_dir }}(/.*)?"
        setype: "{{ container_context_label | default('container_file_t', false) }}"
        state: present
      register: fcontext_set

    - name: Apply Fcontext set above
      become: yes
      ansible.builtin.command: restorecon -irv {{ registry_container_dir }}
      register: fcontext_applied

    - name: '{{ ansible_name_module }} | set_fact |  authfile for destination registry'
      ansible.builtin.set_fact:
        registry_auth_config: "{{ hostvars[inventory_hostname].ansible_env.HOME }}/.docker/config.json"

    - name: '{{ ansible_name_module }} | command | generate authfile for registry'
      no_log: true
      ansible.builtin.command: >
        podman login -u {{ registry_admin_username }} -p {{ registry_admin_password }} \
           --authfile {{ hostvars[inventory_hostname].ansible_env.HOME }}/.docker/config.json \
           {{ registry_host_fqdn }}
      when:
        - "not 'localhost' in registry_host_fqdn"
      register: reg_authfile_created

    - name: '{{ ansible_name_module }} | set imageset config files variable if not set'
      when:
        - not imageset_config_files is defined or (imageset_config_files is defined and not imageset_config_files is mapping and imageset_config_files | type_debug == "list" and imageset_config_files | length == 0)
        - imageset_config_files_dir is defined
        - imageset_config_files_dir != ''
      block:
        - name: '{{ ansible_name_module }} | find |  Find all imageset files'
          ansible.builtin.find:
            path: "{{ imageset_config_files_dir }}"
            recurse: yes
            patterns: '*-imageset-config.yml'
          register: imageset_manifests

        - name: '{{ ansible_name_module }} | set_fact | imageset config file paths'
          ansible.builtin.set_fact:
            imageset_config_files: "{{ imageset_manifests.files | map(attribute='path') | flatten }}"
          when:
            - imageset_manifests is defined
            - imageset_manifests.files is defined
            - imageset_manifests.files | length > 0

        - name: '{{ ansible_name_module }} | Print imageset config files output'
          ansible.builtin.debug:
            var: imageset_config_files
            verbosity: 2

    - name: '{{ ansible_name_module }} | block | unpack bundle to controller if required'
      when:
        - unpack_bundle is defined
        - unpack_bundle | bool
      block:
        - name: '{{ ansible_name_module }} | file:directory | Ensure the operator images staging directory exist'
          file:
            path: "{{ item }}"
            state: directory
            mode: 0755
          loop:
            - "{{ dir_bundle_location }}"

        - name: '{{ ansible_name_module }} | unarchive:xz | original operator bundle on registry '
          unarchive:
            src: "{{ operator_bundle_file_location }}"
            remote_src: yes
            dest: "{{ dir_bundle_location }}"
            mode: 0755
          register: op_unbundle_out

    - name: '{{ ansible_name_module }} | set_fact | custom catalog'
      ansible.builtin.set_fact:
        custom_catalog_names: "{{ custom_catalog_names | d([]) + [{'name': item, 'catalog': (lookup('file', item) | from_yaml).mirror.operators[0].targetName , 'tag': (lookup('file', item) | from_yaml).mirror.operators[0].targetTag }] }}"
      loop: "{{ imageset_config_files }}"
      when:
        - operator_content_type is defined
        - operator_content_type | bool

    - name: '{{ ansible_name_module }} | Print custom tag data output'
      ansible.builtin.debug:
        var: custom_catalog_names
        verbosity: 2

    - name: '{{ ansible_name_module }} | stat | Check if  bundle file exist'
      ansible.builtin.stat:
        path: "{{ dir_bundle_location }}/{{ (item  | basename).split('.')[0] }}.tar"
        get_checksum: false
      loop: "{{ imageset_config_files }}"
      register: bundle_exist

    - name: '{{ ansible_name_module }} | Print bundle exist check output'
      ansible.builtin.debug:
        var: item
        verbosity: 2
      loop: "{{ bundle_exist.results }}"

    - name: '{{ ansible_name_module }} | ansible.builtin.shell | Process content push using imageset  catalogs config files'
      include_tasks: tasks/process-content-push-using-oc-mirror.yml
      loop: "{{ imageset_config_files }}"
      loop_control:
        index_var: key_cnt
      vars:
        imageset_config_file: "{{ item }}"
        bundle_name: "{{ (item  | basename).split('.')[0] }}.tar"
        catalog_index_name: "{{ custom_catalog_names[key_cnt].catalog if custom_catalog_names[key_cnt].catalog is defined and custom_catalog_names[key_cnt].catalog != '' else ('custom-' + item.split('-imageset')[0]) if use_manifest_file is defined and use_manifest_file | bool else '' }}"
        catalog_index_tag: "{{ custom_catalog_names[key_cnt].tag if custom_catalog_names[key_cnt].tag is defined and custom_catalog_names[key_cnt].catalog != '' else '' }}"
        manifests_dir: "{{ playbook_dir }}/manifests/{{ (item | basename).split('-imageset')[0] }}-index-manifests"
        manifest_prefix: "{{ (item | basename).split('-imageset')[0] }}"
      when:
        - bundle_exist.results[key_cnt].stat is defined
        - bundle_exist.results[key_cnt].stat.exists is defined
        - bundle_exist.results[key_cnt].stat.exists | bool
        - bundle_exist.results[key_cnt].stat.path is defined
        - bundle_name in bundle_exist.results[key_cnt].stat.path
      register: all_bundle_processed

    - name: '{{ ansible_name_module }} | Print Manifest extraction output'
      ansible.builtin.debug:
        var: all_bundle_processed.results
        verbosity: 2

    - name: '{{ ansible_name_module }} | ansible.builtin.shell | Generate manifests from imageset catalogs config files '
      include_tasks: tasks/retrieve-manifests-from-oc-mirror-bundle.yml
      loop: "{{ imageset_config_files }}"
      loop_control:
        index_var: key_cnt
      vars:
        imageset_config_file: "{{ item }}"
        bundle_name: "{{ (item  | basename).split('.')[0] }}.tar"
        catalog_index_name: "{{ custom_catalog_names[key_cnt].catalog if custom_catalog_names[key_cnt].catalog is defined and custom_catalog_names[key_cnt].catalog != '' else ('custom-' + item.split('-imageset')[0]) if use_manifest_file is defined and use_manifest_file | bool else '' }}"
        catalog_index_tag: "{{ custom_catalog_names[key_cnt].tag if custom_catalog_names[key_cnt].tag is defined and custom_catalog_names[key_cnt].catalog != '' else '' }}"
        manifests_dir: "{{ playbook_dir }}/manifests/{{ (item | basename).split('-imageset')[0] }}-index-manifests"
        manifest_prefix: "{{ (item | basename).split('-imageset')[0] }}"
      when:
        - bundle_exist.results[key_cnt].stat is defined
        - bundle_exist.results[key_cnt].stat.exists is defined
        - bundle_exist.results[key_cnt].stat.exists | bool
        - bundle_exist.results[key_cnt].stat.path is defined
        - bundle_name in bundle_exist.results[key_cnt].stat.path
      register: all_bundle_manifest_processed

    - name: '{{ ansible_name_module }} | Print Manifest extraction output'
      ansible.builtin.debug:
        var: all_bundle_manifest_processed.results
        verbosity: 2

