kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
mirror:
  operators:
  - catalog: registry.redhat.io/redhat/community-operator-index:v4.12
    targetName: cert-manager
    targetTag: v4.12
    packages:
    - name: cert-manager
      channels:
      - name: "stable"

