kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.20
    targetCatalog: elasticsearch-operator
    targetTag: v4.20
    packages:
    - name: elasticsearch-operator
      channels:
      - name: "stable-5.8"
      - name: "stable-5.7"

