kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
#storageConfig:
#  registry:
#    imageURL: localhost:5000/metadata:latest
#    skipTLS: true
mirror:
  additionalImages:
    - name: registry.redhat.io/rhel8/rhel-guest-image:8.9.0-324
    - name: registry.redhat.io/rhel9/rhel-guest-image:9.3-870
