kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.20
    targetCatalog: rhbk-operator
    targetTag: v4.20
    packages:
    - name: rhbk-operator
      channels:
      - name: "stable-v22"

