kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
mirror:
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.12
    targetName: web-terminal
    targetTag: v4.12
    packages:
    - name: web-terminal
      channels:
      - name: "fast"

