kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
#storageConfig:
#  registry:
#    imageURL: localhost:5000/metadata:latest
#    skipTLS: true
mirror:
  platform:
    channels:
    - name: stable-4.12
      #maxVersion: 4.12.47
      type: ocp
    graph: true
